### PR TITLE
fix: Zero values are used instead of DEFAULT

### LINKED ISSUE #7: Receiving `0` for go-pg fields that are int will insert NULL instead of `0`
Seeing this error from tick which is causing it to die:
`2021/12/14 21:49:38 ERROR #23502 null value in column "volume_base_24h" of relation "quotes" violates not-null constraint`

### PR DESCRIPTION
**Pull request by placer14**
fixes #7

### CODE REVIEW

File: model.go [hunk 1]
```diff
@@ -13,9 +13,9 @@ const schema = "currencies"
 type Quote struct {
 	//lint:ignore U1000 hit for go-pg
 	tableName     struct{} `pg:"currencies.quotes"`
-	Height        int64    `pg:",pk,notnull"`
-	Price         int64    `pg:",notnull"`
-	VolumeBase24h int64    `pg:"volume_base_24h,notnull"`
+	Height        int64    `pg:",pk,notnull,use_zero"`
```
Comment (hsanjuan) [inline model.go:16]: I don't think we should ever insert a 0 height

**Review by hsanjuan — COMMENTED** [review]
I'm unhappy that the process died over this. I'm not sure I want to insert 0s into the database though (it feels like hiding the problems under the rug).

Do we know if CMC responses were valid to all effects or we're missing checks (there's a check for error message)?

**Comment by placer14** [comment]
It seemed the failure mode here was that CMC had a successful, perfectly-valid, well-formed response with bad data included (and our checks don't protect us from "incorrect" data). I just so happened that this case aligns perfectly to expose a bug in our schema. It does appear we do the appropriate checks for bad requests/responses but nothing which inspects the data for correctness.

Unsure if you're aware, I saw `0` values in that column in the earliest rows in our analysis dataset, so it's already happened to some degree.

This fix intends to only protect us from the schema bug without consideration for the correctness of the data. If there are missing protections here (don't allow zero), I'm happy to include them (be sure to mention what the desired behavior should be when zeros are detected).

File: model.go (hunk 1 above)
Comment (placer14) [reply model.go:16]: I'm happy to remove this from the height, but if it were 0 for {whatever} reason, it would fail in the same way. The alternative approach would be to fix the default values for these columns in the schema, but I don't see where that's managed. I think we should do one or the other. Let me know how you'd like the schema change applied if we're going the other way here.

**Comment by hsanjuan** [comment]
Pre-approved pending leaving `height` as it was.
